// d开头是借方，c开头的是贷方，b开头的是余额
// bExRate-汇率 bQty-数量 bPrice-单价 bStadAmt-本币 bCurrAmt-外币

//三栏式
export const tableColumnsSANLAN = [
  {
    title: '期初余额',
    align: 'center',
    children: [
      {
        title: '借方',
        field: 'begDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方',
        field: 'begCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '本期发生额',
    align: 'center',
    children: [
      {
        title: '借方',
        field: 'cDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 80,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方',
        field: 'cCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 80,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '期末余额',
    align: 'center',
    children: [
      {
        title: '借方',
        field: 'endDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方',
        field: 'endCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
]
//数量式
export const tableColumnsSHULIANG = [
  {
    title: '期初余额',
    align: 'center',
    children: [
      {
        title: '方向',
        field: 'begBalSign',
        headerAlign: 'center',
        align: 'left',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '数量',
        field: 'begQtyBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 60,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '金额',
        field: 'begBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '本期发生额',
    align: 'center',
    children: [
      {
        title: '借方数量',
        field: 'cQtyDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '借方金额',
        field: 'cDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 60,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方数量',
        field: 'cQtyCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '贷方金额',
        field: 'cCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '期末余额',
    align: 'center',
    children: [
      {
        title: '方向',
        field: 'endBalSign',
        headerAlign: 'center',
        align: 'left',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '数量',
        field: 'endQtyBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 60,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '金额',
        field: 'endBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
]
//外币式
export const tableColumnsWAIBI = [
  {
    title: '外币',
    field: 'curCode',
    headerAlign: 'center',
    align: 'left',
    minWidth: 60,
    cellRender: { name: 'searchHighLight' },
  },
  {
    title: '期初余额',
    align: 'center',
    children: [
      {
        title: '方向',
        field: 'begBalSign',
        headerAlign: 'center',
        align: 'left',
        minWidth: 120,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '外币金额',
        field: 'begCurBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '金额',
        field: 'begBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '本期发生额',
    align: 'center',
    children: [
      {
        title: '借方外币',
        field: 'cCurDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '借方金额',
        field: 'cDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方外币',
        field: 'cCurCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方金额',
        field: 'cCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '期末余额',
    align: 'center',
    children: [
      {
        title: '方向',
        field: 'endBalSign',
        headerAlign: 'center',
        align: 'left',
        minWidth: 120,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '外币金额',
        field: 'endCurBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '金额',
        field: 'endBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 120,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
]
//数量外币式
export const tableColumnsSHULWAIB = [
  {
    title: '外币',
    field: 'curCode',
    headerAlign: 'center',
    align: 'left',
    minWidth: 60,
    cellRender: { name: 'searchHighLight' },
  },
  {
    title: '期初余额',
    align: 'center',
    children: [
      {
        title: '方向',
        field: 'begBalSign',
        headerAlign: 'center',
        align: 'left',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '数量',
        field: 'begQtyBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 60,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '外币金额',
        field: 'begCurBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '金额',
        field: 'begBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '本期发生额',
    align: 'center',
    children: [
      {
        title: '借方数量',
        field: 'cQtyDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '借方外币',
        field: 'cCurDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '借方金额',
        field: 'cDrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方数量',
        field: 'cQtyCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '贷方外币',
        field: 'cCurCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '贷方金额',
        field: 'cCrAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
  {
    title: '期末余额',
    align: 'center',
    children: [
      {
        title: '方向',
        field: 'endBalSign',
        headerAlign: 'center',
        align: 'left',
        minWidth: 100,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '数量',
        field: 'endQtyBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 60,
        cellRender: { name: 'searchHighLight' },
      },
      {
        title: '外币金额',
        field: 'endCurBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
      {
        title: '金额',
        field: 'endBalAmt',
        headerAlign: 'center',
        align: 'right',
        minWidth: 100,
        cellRender: { name: 'moneyHighLight' },
      },
    ],
  },
]
